Repository kekef2002/Autobody-Shop-Application-Project, pull requests merged in 2024-12, with the labels that each got.

#98 About us and Collison
  src/main/java/edu/farmingdale/autobodyshopapplicationproject/AboutUsController.java
  src/main/java/edu/farmingdale/autobodyshopapplicationproject/AutoRepairsAndMaintenanceController.java
  src/main/java/edu/farmingdale/autobodyshopapplicationproject/CollisonRepairController.java
  src/main/resources/edu/farmingdale/autobodyshopapplicationproject/about-us.css
  src/main/resources/edu/farmingdale/autobodyshopapplicationproject/about-us.fxml
  src/main/resources/edu/farmingdale/autobodyshopapplicationproject/collision-repairs-page.fxml
  src/main/resources/edu/farmingdale/autobodyshopapplicationproject/collision-repairs.css
  src/main/resources/edu/farmingdale/autobodyshopapplicationproject/phone_iphone_24dp_E8EAED_FILL0_wght400_GRAD0_opsz24.png
  src/main/resources/edu/farmingdale/autobodyshopapplicationproject/v14_48.png
  src/main/resources/edu/farmingdale/autobodyshopapplicationproject/v15_147.png
  src/main/resources/edu/farmingdale/autobodyshopapplicationproject/v169_10.png
  src/main/resources/edu/farmingdale/autobodyshopapplicationproject/v172_33.png
  src/main/resources/edu/farmingdale/autobodyshopapplicationproject/v208_15.png
  src/main/resources/edu/farmingdale/autobodyshopapplicationproject/v87_5.png
Labels: enhancement

#99 28 build screen check engine light diagnostics
  src/main/java/edu/farmingdale/autobodyshopapplicationproject/CELDController.java
  src/main/resources/edu/farmingdale/autobodyshopapplicationproject/celd-page.fxml
  src/main/resources/edu/farmingdale/autobodyshopapplicationproject/celd.css
  src/main/resources/edu/farmingdale/autobodyshopapplicationproject/v130_14.png
  src/main/resources/edu/farmingdale/autobodyshopapplicationproject/v15_83.png
  src/main/resources/gallery/css/main.css
  src/main/resources/gallery/gallery-page.fxml
  src/main/resources/gallery/gallery.css
  src/main/resources/gallery/images/v150_7.png
  src/main/resources/gallery/images/v193_18.png
  src/main/resources/gallery/images/v193_21.png
  src/main/resources/gallery/images/v201_24.png
  src/main/resources/gallery/images/v201_27.png
  src/main/resources/gallery/images/v201_30.png
  src/main/resources/gallery/images/v201_33.png
  src/main/resources/gallery/images/v201_36.png
  src/main/resources/gallery/images/v201_39.png
  src/main/resources/gallery/index.html
Labels: enhancement

#104 2-establish-database-server-connection
  src/main/java/edu/farmingdale/autobodyshopapplicationproject/dao/DbConnection.java
  src/main/java/edu/farmingdale/autobodyshopapplicationproject/model/Person.java
  src/main/java/module-info.java
Labels: enhancement

#107 created a powerpoint
  Documentations/Group1_Project.pptx
  src/main/java/edu/farmingdale/autobodyshopapplicationproject/controllers/HelloController.java
Labels: documentation

#110 I created an AbstractController.java for Reusability: The loadScene m…
  src/main/java/edu/farmingdale/autobodyshopapplicationproject/MainApplication.java
  src/main/java/edu/farmingdale/autobodyshopapplicationproject/controllers/AboutUsController.java
  src/main/java/edu/farmingdale/autobodyshopapplicationproject/controllers/AbstractController.java
  src/main/java/edu/farmingdale/autobodyshopapplicationproject/controllers/AppointmentController.java
  src/main/java/edu/farmingdale/autobodyshopapplicationproject/controllers/AutoGlassReplacementController.java
  src/main/java/edu/farmingdale/autobodyshopapplicationproject/controllers/AutoRepairsAndMaintenanceController.java
  src/main/java/edu/farmingdale/autobodyshopapplicationproject/controllers/CELDController.java
  src/main/java/edu/farmingdale/autobodyshopapplicationproject/controllers/CollisionRepairController.java
  src/main/java/edu/farmingdale/autobodyshopapplicationproject/controllers/CreateAccountController.java
  src/main/java/edu/farmingdale/autobodyshopapplicationproject/controllers/GalleryController.java
  src/main/java/edu/farmingdale/autobodyshopapplicationproject/controllers/HomeController.java
  src/main/java/edu/farmingdale/autobodyshopapplicationproject/controllers/LoginController.java
  src/main/resources/edu/farmingdale/autobodyshopapplicationproject/fxml/create-account-page.fxml
Labels: bug

#112 I created a NextAppointmentController class and next-appointment.fxml…
  src/main/java/edu/farmingdale/autobodyshopapplicationproject/controllers/AppointmentController.java
  src/main/java/edu/farmingdale/autobodyshopapplicationproject/controllers/LoginController.java
  src/main/java/edu/farmingdale/autobodyshopapplicationproject/controllers/NextAppointmentController.java
  src/main/java/edu/farmingdale/autobodyshopapplicationproject/dao/DbConnection.java
  src/main/resources/edu/farmingdale/autobodyshopapplicationproject/fxml/next-appointment.fxml
  src/main/resources/edu/farmingdale/autobodyshopapplicationproject/images/side_view_car_right.jpg
Labels: enhancement, refactor

#114 Documention
  Documentations/Auto Body Shop Project Overview.docx
Labels: documentation
