Repository kekef2002/Autobody-Shop-Application-Project, pull requests merged in 2024-11, with the labels that each got.

#69 18 build screen home
  .idea/vcs.xml
  src/main/java/edu/farmingdale/autobodyshopapplicationproject/HelloApplication.java
  src/main/resources/edu/farmingdale/autobodyshopapplicationproject/home-page.fxml
  src/main/resources/edu/farmingdale/autobodyshopapplicationproject/home.css
  src/main/resources/edu/farmingdale/autobodyshopapplicationproject/v13_14.png
  src/main/resources/edu/farmingdale/autobodyshopapplicationproject/v13_28.png
Labels: enhancement, priority::critical

#70 I created a Controller file for the home page
  src/main/java/edu/farmingdale/autobodyshopapplicationproject/HomeController.java
  src/main/resources/edu/farmingdale/autobodyshopapplicationproject/home-page.fxml
Labels: enhancement

#71 27 build screen appointment
  src/main/resources/edu/farmingdale/autobodyshopapplicationproject/Painting bumper.jpg
  src/main/resources/edu/farmingdale/autobodyshopapplicationproject/Speedometer3.jpg
  src/main/resources/edu/farmingdale/autobodyshopapplicationproject/appointment-page.fxml
  src/main/resources/edu/farmingdale/autobodyshopapplicationproject/appointment.css
  src/main/resources/edu/farmingdale/autobodyshopapplicationproject/v15_227.png
Labels: enhancement

#72 Add files via upload
  splashscreen-page.fxml
  splashscreen.css
Labels: enhancement

#75 I created the AppointmentController file, and it is ready for review …
  src/main/java/edu/farmingdale/autobodyshopapplicationproject/AppointmentController.java
Labels: enhancement

#76 Auto-repair and Maintaince Screen Done
  .idea/misc.xml
  .idea/vcs.xml
  src/main/resources/edu/farmingdale/autobodyshopapplicationproject/auto-repairs-and-maintenance-page.fxml
  src/main/resources/edu/farmingdale/autobodyshopapplicationproject/auto-repairs-and-maintenance.css
  src/main/resources/edu/farmingdale/autobodyshopapplicationproject/images/v15_67.png
  src/main/resources/edu/farmingdale/autobodyshopapplicationproject/images/v164_30.png
  src/main/resources/edu/farmingdale/autobodyshopapplicationproject/images/v164_31.png
  src/main/resources/edu/farmingdale/autobodyshopapplicationproject/images/v164_32.png
Labels: enhancement

#78 Added a Group node containing a MenuButton for "Services" with submen…
  src/main/resources/edu/farmingdale/autobodyshopapplicationproject/auto-repairs-and-maintenance-page.fxml
  src/main/resources/edu/farmingdale/autobodyshopapplicationproject/auto-repairs-and-maintenance.css
Labels: refactor

#83 Add files via upload
  src/main/resources/edu/farmingdale/autobodyshopapplicationproject/auto-glass-replacement/auto-glass-replacement-page.fxml
  src/main/resources/edu/farmingdale/autobodyshopapplicationproject/auto-glass-replacement/auto-glass-replacement.css
  src/main/resources/edu/farmingdale/autobodyshopapplicationproject/auto-glass-replacement/css/main.css
  src/main/resources/edu/farmingdale/autobodyshopapplicationproject/auto-glass-replacement/images/v15_131.png
  src/main/resources/edu/farmingdale/autobodyshopapplicationproject/auto-glass-replacement/images/v235_15.png
  src/main/resources/edu/farmingdale/autobodyshopapplicationproject/auto-glass-replacement/images/v250_32.png
  src/main/resources/edu/farmingdale/autobodyshopapplicationproject/auto-glass-replacement/index.html
  src/main/resources/edu/farmingdale/autobodyshopapplicationproject/gallery/css/main.css
  src/main/resources/edu/farmingdale/autobodyshopapplicationproject/gallery/gallery-page.fxml
  src/main/resources/edu/farmingdale/autobodyshopapplicationproject/gallery/gallery.css
  src/main/resources/edu/farmingdale/autobodyshopapplicationproject/gallery/images/v150_7.png
  src/main/resources/edu/farmingdale/autobodyshopapplicationproject/gallery/images/v193_18.png
  src/main/resources/edu/farmingdale/autobodyshopapplicationproject/gallery/images/v193_21.png
  src/main/resources/edu/farmingdale/autobodyshopapplicationproject/gallery/images/v201_24.png
  src/main/resources/edu/farmingdale/autobodyshopapplicationproject/gallery/images/v201_27.png
  src/main/resources/edu/farmingdale/autobodyshopapplicationproject/gallery/images/v201_30.png
  src/main/resources/edu/farmingdale/autobodyshopapplicationproject/gallery/images/v201_33.png
  src/main/resources/edu/farmingdale/autobodyshopapplicationproject/gallery/images/v201_36.png
  src/main/resources/edu/farmingdale/autobodyshopapplicationproject/gallery/images/v201_39.png
  src/main/resources/edu/farmingdale/autobodyshopapplicationproject/gallery/index.html
Labels: enhancement

#81 Created the controller page for the auto and maintenance repair
  src/main/java/edu/farmingdale/autobodyshopapplicationproject/AutoRepairsAndMaintenanceController.java
Labels: bug

#84 login page fxml and css
  src/main/resources/edu/farmingdale/autobodyshopapplicationproject/login-page.fxml
  src/main/resources/edu/farmingdale/autobodyshopapplicationproject/login.css
Labels: enhancement

#85 82 implementing button functionality on the home page
  .idea/misc.xml
  src/main/java/edu/farmingdale/autobodyshopapplicationproject/HomeController.java
  src/main/resources/edu/farmingdale/autobodyshopapplicationproject/auto-repairs-and-maintenance.css
  src/main/resources/edu/farmingdale/autobodyshopapplicationproject/gallery/gallery-page.fxml
  src/main/resources/edu/farmingdale/autobodyshopapplicationproject/home-page.fxml
Labels: bug, refactor

#89 I developed the create account controller file.
  src/main/java/edu/farmingdale/autobodyshopapplicationproject/CreateAccountController.java
Labels: enhancement

#90 55 implement controller auto glass repair
  src/main/java/edu/farmingdale/autobodyshopapplicationproject/GalleryController.java
  src/main/java/edu/farmingdale/autobodyshopapplicationproject/HelloApplication.java
  src/main/resources/edu/farmingdale/autobodyshopapplicationproject/gallery/gallery-page.fxml
  src/main/resources/edu/farmingdale/autobodyshopapplicationproject/gallery/images/hello-view.fxml
Labels: refactor

#91 splashscreen in main
  .idea/misc.xml
  .idea/uiDesigner.xml
  src/main/java/edu/farmingdale/autobodyshopapplicationproject/HelloApplication.java
  src/main/java/module-info.java
  src/main/resources/edu/farmingdale/autobodyshopapplicationproject/splashscreen-page.fxml
Labels: enhancement
